services:
  visguard:
    build: 
      context: .
    container_name: visguard
    restart: unless-stopped
    volumes:
      - ./:/usr/src/visguard
      - /mnt/ADATA64G/camera1/ftp:/usr/src/visguard/ftp
      - /home/aform/videos/main_door:/usr/src/visguard/videos/main_door
    working_dir: /usr/src/visguard
    ports:
      - "8021:8080"
    environment:
      TZ: Europe/Chisinau
    command: ["node", "main.js"]
    user: "1000:1000"