export const EVENTS = {
    SOURCE_CHANGE: 'SOURCE_CHANGE',
    VIDEO_EVENT_START: 'VIDEO_EVENT_START',
    VIDEO_EVENT_END: 'VIDEO_EVENT_END',
}

export const EVENT_TYPES = {
    FILESYSTEM: 'FILESYSTEM',
    HTTP_ENDPOINT: 'HTTP_ENDPOINT',
}